### ISSUE TITLE
Show error modal or snick-bar on new redirect error

### ISSUE THREAD

**Issue by kiselev-nikolay** [kiselev-nikolay/direct-to-me#8]

**Comment by y377** [comment]
My English is very bad. Is this a reverse proxy-like program? For example, redirect web pages outside the firewall to a new url? Until it can be accessed?

**Comment by kiselev-nikolay** [comment]
No, it's a data redirection program. You create a link inside the program `example.com/test-link` that will take data in any format and send it in the background to some web hook (for example send it to your slack), and redirect the user to other links, such as back to the home page.

**Comment by y377** [comment]
Although I don't quite understand it yet, I think I will use it one day, thank you for your open source!

**Comment by kiselev-nikolay** [comment]
![image](https://user-images.githubusercontent.com/55307887/127731973-04759a56-d9cf-4fa3-9c50-61436329d5be.png)
